# Generated by Django 4.1.2 on 2022-10-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friendships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
