# Generated by Django 4.1.2 on 2022-10-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsfeed",
            options={"ordering": ("-created_at",)},
        ),
    ]
