# Generated by Django 4.1.2 on 2022-10-22 07:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0002_alter_tweet_created_at_alter_tweet_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"ordering": ("user", "-created_at")},
        ),
        migrations.AlterIndexTogether(
            name="tweet",
            index_together={("user", "created_at")},
        ),
    ]
