# Generated by Django 4.1.2 on 2022-10-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_auto_20221031_1937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
